name: Building application

on: [ push, pull_request ]

jobs:
  build-all:
    name: 'Building'

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]
        platforms: [ win-x86, win-x64 ]

    env:
      solution_name: Maheirema.sln
      project_path: src/Eixini.Maheirema.Wpf/Eixini.Maheirema.Wpf.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: |
        dotnet restore

    - name: Publishing application
      run: |
        dotnet publish $env:project_path -c Release -p:PublishSingleFile=true -r ${{ matrix.platforms }} --self-contained true -p:IncludeAllContentForSelfExtract=true -p:PublishReadyToRun=true -p:EnableCompressionInSingleFile=true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: publish-${{ matrix.platforms }}
        path: bin/Release/${{ matrix.platforms }}/publish/
